extend type Query {
  self: User
  users(input: UserSearch): UserConnection
}

extend type Mutation {
  assignCallingsToUser(callingIds: [ID!]!, userId: ID!): CallingsAssignmentPayload!
  removeCallingsFromUser(callingIds: [ID!]!, userId: ID!): CallingsAssignmentPayload!
}

type CallingsAssignmentPayload {
  success: Boolean!
  error: CallingsAssignmentError
}

type CallingsAssignmentError implements GenericError {
  code: CallingsAssignmentErrorCodes!
  message: String!
}

enum CallingsAssignmentErrorCodes {
  USER_NOT_FOUND
  CALLING_NOT_FOUND
  INSUFFICIENT_PERMISSIONS
  UNKNOWN_ERROR
}

input UserSearch {
  paging: OffsetPaging
  sorting: [UserSorting!]
  filters: UserFilters
}

input UserSorting {
  field: UserSortField!
  direction: SortDirection!
}

enum UserSortField {
  EMAIL
  FIRST_NAME
  LAST_NAME
  IS_EMAIL_VERIFIED
  IS_SITE_ADMIN
}

input UserFilters {
  emailContains: String
  firstNameContains: String
  lastNameContains: String
  isEmailVerified: Boolean
  isSiteAdmin: Boolean
  hasCalling: Boolean
  callingIsOneOf: [ID!]
  callingIsNotOneOf: [ID!]
}

type UserConnection {
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

type UserEdge {
  node: User!
}

type User {
  id: ID!
  firstName: String!
  lastName: String!
  email: EmailAddress!
  isSiteAdmin: Boolean
  callings: [Calling!]!
}