type AvailabilityBlock {
    start: DateTime
    end: DateTime
    bishopricMember: BishopricMember
    priorityDirection: PriorityDirection
    availableSlot(durationInMinutes: Int!): TimeSlot
}

type TimeSlot {
    start: DateTime
    end: DateTime
}

enum BishopricMember {
    BISHOP
    FIRST_COUNSELOR
    SECOND_COUNSELOR
}

enum PriorityDirection {
    ASC
    DESC
}

type AppointmentPayload {
    timeSlot: TimeSlot
    bishopricMember: BishopricMember
    success: Boolean!
    error: AppointmentError
}

interface GenericError {
    message: String
}

type AppointmentError implements GenericError {
    code: AppointmentErrorCodes
    message: String
}

enum AppointmentErrorCodes {
    APPOINTMENT_CONFLICT
    INVALID_TIME_SLOT
    UNKNOWN_ERROR
}

input AppointmentDetails {
    timeSlot: AppointmentTimeSlot!
    bishopricMember: BishopricMember!
    name: String!
    type: AppointmentCode!
    description: String
}

input AppointmentTimeSlot {
    start: DateTime!
    end: DateTime!
}

type AppointmentType {
    code: AppointmentCode!
    name: String!
    description: String
    durationInMinutes: Int!
    interviewers: [BishopricMember!]!
}

enum AppointmentCode {
    BAPTISM
    ECCLESIASTICAL_ENDORSEMENT
    MISSION
    OTHER
    PATRIARCHAL_BLESSING
    PERSONAL_MATTER_LONG
    PERSONAL_MATTER_SHORT
    TEMPLE_RECOMMEND
    TEMPLE_RECOMMEND_RENEWAL
    TEMPLE_WORKER
    TITHING_DECLARATION
}

extend type Query {
    allAvailabilityBlocks: [AvailabilityBlock!]!
    allAppointmentTypes: [AppointmentType!]!
    availabilityBlocks(bishopricMember: BishopricMember!): [AvailabilityBlock!]!
    availableTimeSlots(bishopricMember: BishopricMember!, durationInMinutes: Int!): [TimeSlot]!
}

extend type Mutation {
    createAppointment(input: AppointmentDetails!): AppointmentPayload!
}