type AvailabilityBlock {
    start: DateTime
    end: DateTime
    bishopricMember: ID
    priorityDirection: PriorityDirection
    availableSlot(durationInMinutes: Int!): TimeSlot
}

type TimeSlot {
    start: DateTime
    end: DateTime
}

enum PriorityDirection {
    ASC
    DESC
}

type AppointmentPayload {
    timeSlot: TimeSlot
    bishopricMember: ID
    success: Boolean!
    error: AppointmentError
}

interface GenericError {
    message: String
}

type AppointmentError implements GenericError {
    code: AppointmentErrorCodes
    message: String
}

enum AppointmentErrorCodes {
    APPOINTMENT_TYPE_NOT_FOUND
    APPOINTMENT_CONFLICT
    INVALID_TIME_SLOT
    UNKNOWN_ERROR
}

input AppointmentDetails {
    id: ID!
    timeSlot: AppointmentTimeSlot!
    bishopricMember: ID!
    name: String!
    description: String
}

input AppointmentTimeSlot {
    start: DateTime!
    end: DateTime!
}

type AppointmentType {
    id: ID!
    name: String!
    description: String
    durationInMinutes: Int!
    interviewers: [ID!]!
}

extend type Query {
    allAvailabilityBlocks: [AvailabilityBlock!]!
    allAppointmentTypes: [AppointmentType!]!
    availabilityBlocks(bishopricMember: ID!): [AvailabilityBlock!]!
    availableTimeSlots(bishopricMember: ID!, durationInMinutes: Int!): [TimeSlot]!
}

extend type Mutation {
    createAppointment(input: AppointmentDetails!): AppointmentPayload!
}