input AppointmentDetails {
  bishopricMember: ID!
  description: String
  id: ID!
  name: String!
  timeSlot: AppointmentTimeSlot!
}

type AppointmentError implements GenericError {
  code: AppointmentErrorCodes
  message: String
}

enum AppointmentErrorCodes {
  APPOINTMENT_CONFLICT
  APPOINTMENT_TYPE_NOT_FOUND
  INVALID_TIME_SLOT
  UNKNOWN_ERROR
}

type AppointmentPayload {
  bishopricMember: ID
  error: AppointmentError
  success: Boolean!
  timeSlot: TimeSlot
}

input AppointmentTimeSlot {
  end: DateTime!
  start: DateTime!
}

type AppointmentType {
  description: String
  durationInMinutes: Int!
  id: ID!
  interviewers: [ID!]!
  name: String!
}

type AvailabilityBlock {
  availableSlot(durationInMinutes: Int!): TimeSlot
  bishopricMember: ID
  end: DateTime
  priorityDirection: PriorityDirection
  start: DateTime
}

input Credentials {
  email: EmailAddress!
  password: String!
}

scalar DateTime

scalar EmailAddress

interface GenericError {
  message: String
}

type LoginError implements GenericError {
  code: LoginErrorCodes
  message: String
}

enum LoginErrorCodes {
  INVALID_CREDENTIALS
  UNKNOWN_ERROR
  USER_NOT_FOUND
}

type LoginPayload {
  error: LoginError
  success: Boolean!
  user: User
}

type LogoutPayload {
  success: Boolean!
}

type Mutation {
  createAppointment(input: AppointmentDetails!): AppointmentPayload!
  login(input: Credentials!): LoginPayload!
  logout: LogoutPayload!
  requestPasswordReset(email: EmailAddress!): RequestPasswordResetPayload!
  resendEmailVerification(email: EmailAddress!): ResendEmailVerificationPayload!
  resetPassword(input: ResetPasswordDetails!): ResetPasswordPayload!
  signUp(input: SignUpDetails!): SignUpPayload!
  verifyEmail(code: Int!, email: EmailAddress!): VerifyEmailPayload!
}

enum PriorityDirection {
  ASC
  DESC
}

type Query {
  allAppointmentTypes: [AppointmentType!]!
  allAvailabilityBlocks: [AvailabilityBlock!]!
  availabilityBlocks(bishopricMember: ID!): [AvailabilityBlock!]!
  availableTimeSlots(bishopricMember: ID!, durationInMinutes: Int!): [TimeSlot]!
  self: User
}

type RequestPasswordResetError implements GenericError {
  code: RequestPasswordResetErrorCodes
  message: String
}

enum RequestPasswordResetErrorCodes {
  COULD_NOT_CREATE
  COULD_NOT_UPDATE
  EMAIL_ERROR
  NOT_FOUND
  PASSWORD_RESET_AGENT_AUTHENTICATION_FAILED
  UNKNOWN_ERROR
}

type RequestPasswordResetPayload {
  error: RequestPasswordResetError
  success: Boolean!
}

type ResendEmailVerificationError implements GenericError {
  code: ResendEmailVerificationErrorCodes
  message: String
}

enum ResendEmailVerificationErrorCodes {
  COULD_NOT_CREATE
  COULD_NOT_UPDATE
  EMAIL_ALREADY_VERIFIED
  EMAIL_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  NOT_FOUND
  UNKNOWN_ERROR
}

type ResendEmailVerificationPayload {
  error: ResendEmailVerificationError
  success: Boolean!
}

input ResetPasswordDetails {
  code: Int!
  email: EmailAddress!
  password: String!
}

type ResetPasswordError implements GenericError {
  code: ResetPasswordErrorCodes
  message: String
}

enum ResetPasswordErrorCodes {
  CODE_EXPIRED
  CODE_INVALID
  DELETE_ERROR
  NOT_FOUND
  PASSWORD_RESET_AGENT_AUTHENTICATION_FAILED
  RESET_ERROR
  UNKNOWN_ERROR
}

type ResetPasswordPayload {
  error: ResetPasswordError
  success: Boolean!
}

input SignUpDetails {
  email: EmailAddress!
  name: String!
  password: String!
}

type SignUpError implements GenericError {
  code: SignUpErrorCodes
  message: String
}

enum SignUpErrorCodes {
  EMAIL_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  INVALID_CREDENTIALS
  INVALID_PASSWORD_CHARACTER
  INVALID_PASSWORD_LENGTH
  MISSING_CAPITAL_LETTER
  MISSING_LOWERCASE_LETTER
  MISSING_NUMBER
  NOT_FOUND
  UNKNOWN_ERROR
}

type SignUpPayload {
  error: SignUpError
  success: Boolean!
}

type TimeSlot {
  end: DateTime
  start: DateTime
}

type User {
  email: EmailAddress!
  id: ID!
  name: String!
}

type VerifyEmailError implements GenericError {
  code: VerifyEmailErrorCodes
  message: String
}

enum VerifyEmailErrorCodes {
  CODE_EXPIRED
  CODE_INVALID
  DELETE_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  NOT_FOUND
  UNKNOWN_ERROR
}

type VerifyEmailPayload {
  error: VerifyEmailError
  success: Boolean!
}