input AppointmentDetails {
  bishopricMember: ID!
  description: String
  id: ID!
  name: String!
  timeSlot: AppointmentTimeSlot!
}

type AppointmentError implements GenericError {
  code: AppointmentErrorCodes
  message: String
}

enum AppointmentErrorCodes {
  APPOINTMENT_CONFLICT
  APPOINTMENT_TYPE_NOT_FOUND
  INVALID_TIME_SLOT
  UNKNOWN_ERROR
}

type AppointmentPayload {
  bishopricMember: ID
  error: AppointmentError
  success: Boolean!
  timeSlot: TimeSlot
}

input AppointmentTimeSlot {
  end: DateTime!
  start: DateTime!
}

type AppointmentType {
  description: String
  durationInMinutes: Int!
  id: ID!
  interviewers: [ID!]!
  name: String!
}

type AvailabilityBlock {
  availableSlot(durationInMinutes: Int!): TimeSlot
  bishopricMember: ID
  end: DateTime
  priorityDirection: PriorityDirection
  start: DateTime
}

type Calling {
  assignedTo: [User!]!
  id: ID!
  name: String!
  permissions: [Permission!]!
}

type CallingConnection {
  edges: [CallingEdge!]!
  pageInfo: PageInfo!
}

type CallingEdge {
  node: Calling!
}

input CallingFilters {
  isAssigned: Boolean
  nameContains: String
}

input CallingSearch {
  filters: CallingFilters
  paging: OffsetPaging
}

input Credentials {
  email: EmailAddress!
  password: String!
}

scalar DateTime

scalar EmailAddress

interface GenericError {
  message: String
}

type LoginError implements GenericError {
  code: LoginErrorCodes
  message: String
}

enum LoginErrorCodes {
  INVALID_CREDENTIALS
  UNKNOWN_ERROR
  USER_NOT_FOUND
}

type LoginPayload {
  error: LoginError
  success: Boolean!
  user: User
}

type LogoutPayload {
  success: Boolean!
}

type Mutation {
  changeMyTriviaPlayerName(newName: String!): TriviaGamePayload!
  closeTriviaGame: TriviaGamePayload!
  createAppointment(input: AppointmentDetails!): AppointmentPayload!
  createPermission(input: PermissionCreate!): PermissionPayload!
  createTriviaGame(gameId: ID!): TriviaGamePayload!
  deletePermission(id: ID!): PermissionDeletePayload!
  login(input: Credentials!): LoginPayload!
  logout: LogoutPayload!
  nextTriviaQuestion: TriviaGamePayload!
  pauseTriviaGame: TriviaGamePayload!
  requestPasswordReset(email: EmailAddress!): RequestPasswordResetPayload!
  resendEmailVerification(email: EmailAddress!): ResendEmailVerificationPayload!
  resetPassword(input: ResetPasswordDetails!): ResetPasswordPayload!
  resumeTriviaGame: TriviaGamePayload!
  showScoreAfterQuestion: TriviaGamePayload!
  showScoreImmediately: TriviaGamePayload!
  signUp(input: SignUpDetails!): SignUpPayload!
  startTriviaGame(gameId: ID!): TriviaGamePayload!
  stopTriviaGame: TriviaGamePayload!
  submitTriviaAnswer(answer: TriviaAnswer!): TriviaGamePayload!
  verifyEmail(code: Int!, email: EmailAddress!): VerifyEmailPayload!
}

input OffsetPaging {
  limit: Int = 20
  offset: Int = 0
}

type PageInfo {
  hasNextPage: Boolean!
  pageOffset: Int!
  pageSize: Int!
  totalCount: Int!
}

type Permission {
  callings: [Calling!]!
  id: ID!
  name: String!
}

type PermissionAssociateCallingsError {
  code: PermissionAssociateCallingsErrorCode!
  message: String!
}

enum PermissionAssociateCallingsErrorCode {
  CALLING_NOT_FOUND
  UNEXPECTED_ERROR
}

type PermissionAssociateCallingsPayload {
  callings: [Calling!]!
  error: PermissionAssociateCallingsError
  success: Boolean!
}

type PermissionConnection {
  edges: [PermissionEdge!]!
  pageInfo: PageInfo!
}

input PermissionCreate {
  callings: [ID!]
  name: String!
}

type PermissionDeleteError {
  code: PermissionDeleteErrorCode!
  message: String!
}

enum PermissionDeleteErrorCode {
  PERMISSION_NOT_FOUND
  UNEXPECTED_ERROR
}

type PermissionDeletePayload {
  error: PermissionDeleteError
  success: Boolean!
}

type PermissionEdge {
  node: Permission!
}

type PermissionError {
  code: PermissionErrorCode!
  message: String!
}

enum PermissionErrorCode {
  INVALID_PERMISSION_NAME
  PERMISSION_ALREADY_EXISTS
  UNEXPECTED_ERROR
}

input PermissionFilters {
  callingIsNotOneOf: [ID!]
  callingIsOneOf: [ID!]
  nameContains: String
}

type PermissionPayload {
  error: PermissionError
  permission: Permission
  success: Boolean!
}

input PermissionSearch {
  filters: PermissionFilters
  paging: OffsetPaging
}

type PlayerScore {
  playerName: String!
  score: Int!
}

enum PriorityDirection {
  ASC
  DESC
}

type Query {
  allAppointmentTypes: [AppointmentType!]!
  allAvailabilityBlocks: [AvailabilityBlock!]!
  availabilityBlocks(bishopricMember: ID!): [AvailabilityBlock!]!
  availableTimeSlots(bishopricMember: ID!, durationInMinutes: Int!): [TimeSlot]!
  callings(input: CallingSearch): CallingConnection
  currentGame: TriviaGame
  myTriviaScore: [TriviaPlayerScore!]!
  permissions(input: PermissionSearch): PermissionConnection
  self: User
  users(input: UserSearch): UserConnection
}

type RequestPasswordResetError implements GenericError {
  code: RequestPasswordResetErrorCodes
  message: String
}

enum RequestPasswordResetErrorCodes {
  COULD_NOT_CREATE
  COULD_NOT_UPDATE
  EMAIL_ERROR
  NOT_FOUND
  PASSWORD_RESET_AGENT_AUTHENTICATION_FAILED
  UNKNOWN_ERROR
}

type RequestPasswordResetPayload {
  error: RequestPasswordResetError
  success: Boolean!
}

type ResendEmailVerificationError implements GenericError {
  code: ResendEmailVerificationErrorCodes
  message: String
}

enum ResendEmailVerificationErrorCodes {
  COULD_NOT_CREATE
  COULD_NOT_UPDATE
  EMAIL_ALREADY_VERIFIED
  EMAIL_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  NOT_FOUND
  UNKNOWN_ERROR
}

type ResendEmailVerificationPayload {
  error: ResendEmailVerificationError
  success: Boolean!
}

input ResetPasswordDetails {
  code: Int!
  email: EmailAddress!
  password: String!
}

type ResetPasswordError implements GenericError {
  code: ResetPasswordErrorCodes
  message: String
}

enum ResetPasswordErrorCodes {
  CODE_EXPIRED
  CODE_INVALID
  DELETE_ERROR
  NOT_FOUND
  PASSWORD_RESET_AGENT_AUTHENTICATION_FAILED
  RESET_ERROR
  UNKNOWN_ERROR
}

type ResetPasswordPayload {
  error: ResetPasswordError
  success: Boolean!
}

input SignUpDetails {
  email: EmailAddress!
  firstName: String!
  lastName: String!
  password: String!
}

type SignUpError implements GenericError {
  code: SignUpErrorCodes
  message: String
}

enum SignUpErrorCodes {
  EMAIL_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  INVALID_CREDENTIALS
  INVALID_PASSWORD_CHARACTER
  INVALID_PASSWORD_LENGTH
  MISSING_CAPITAL_LETTER
  MISSING_LOWERCASE_LETTER
  MISSING_NUMBER
  NOT_FOUND
  UNKNOWN_ERROR
}

type SignUpPayload {
  error: SignUpError
  success: Boolean!
}

enum SortDirection {
  ASC
  DESC
}

type Subscription {
  joinTriviaGameAsAdmin: TriviaGameUpdateForAdmin!
  joinTriviaGameAsBoard: TriviaGameUpdateForBoard!
  joinTriviaGameAsPlayer: TriviaGameUpdateForPlayer!
}

type TimeSlot {
  end: DateTime
  start: DateTime
}

enum TriviaAnswer {
  A
  B
  C
  D
}

type TriviaGame {
  id: ID!
}

type TriviaGameError implements GenericError {
  code: TriviaGameErrorCodes
  message: String
}

enum TriviaGameErrorCodes {
  GAME_ALREADY_EXISTS
  GAME_NOT_FOUND
  INSUFFICIENT_PERMISSIONS
  UNKNOWN_ERROR
}

type TriviaGamePayload {
  error: TriviaGameError
  success: Boolean!
}

type TriviaGameScore {
  category: String!
  scores: [PlayerScore!]!
}

enum TriviaGameState {
  ANSWER
  CLOSED
  PAUSED
  QUESTION
  SCORE
  SPLASH
  STOPPED
}

type TriviaGameUpdateForAdmin {
  question: TriviaQuestion
  state: TriviaGameState!
  time: Int
}

type TriviaGameUpdateForBoard {
  question: TriviaQuestion
  scores: [TriviaGameScore!]
  state: TriviaGameState!
  time: Int
}

type TriviaGameUpdateForPlayer {
  question: TriviaQuestion
  state: TriviaGameState!
  time: Int
}

type TriviaOption {
  option: TriviaAnswer!
  text: String!
}

type TriviaPlayerScore {
  category: String!
  score: Int!
}

type TriviaQuestion {
  category: String!
  correctAnswer: TriviaAnswer
  options: [TriviaOption!]!
  question: String!
}

type User {
  callings: [Calling!]!
  email: EmailAddress!
  firstName: String!
  id: ID!
  isSiteAdmin: Boolean
  lastName: String!
}

type UserConnection {
  edges: [UserEdge!]!
  pageInfo: PageInfo!
}

type UserEdge {
  node: User!
}

input UserFilters {
  callingIsOneOf: [ID!]
  emailContains: String
  firstNameContains: String
  hasCalling: Boolean
  isEmailVerified: Boolean
  isSiteAdmin: Boolean
  lastNameContains: String
}

input UserSearch {
  filters: UserFilters
  paging: OffsetPaging
  sorting: [UserSorting!]
}

enum UserSortField {
  EMAIL
  FIRST_NAME
  IS_EMAIL_VERIFIED
  IS_SITE_ADMIN
  LAST_NAME
}

input UserSorting {
  direction: SortDirection!
  field: UserSortField!
}

type VerifyEmailError implements GenericError {
  code: VerifyEmailErrorCodes
  message: String
}

enum VerifyEmailErrorCodes {
  CODE_EXPIRED
  CODE_INVALID
  DELETE_ERROR
  EMAIL_VERIFIER_AUTHENTICATION_FAILED
  NOT_FOUND
  UNKNOWN_ERROR
}

type VerifyEmailPayload {
  error: VerifyEmailError
  success: Boolean!
}